### PR TITLE
Return exit code if there is a breaking change

### PR DESCRIPTION
**Pull request by tomchipchase**
I'd like to run this in our CI pipeline to prevent breaking changes being merged.

This change returns a non-zero exit code if there are breaking changes, which will cause a CI pipeline looking at exit codes to fail.

### CODE REVIEW

**Comment by xuorig** [comment]
Thanks for this, really nice to run this in CI. 

What do you think about adding a command to the CLI that was explicitly made for these scenarios? I worry exiting with an error since the command initially was just to compare / see the changes.

I definitely think it would be great to add a `./schema-comparator verify schema_a.graphql schema_b.graphql` or something similar.

**Comment by tomchipchase** [comment]
I'm happy to add something like that.

An alternative to a new subcommand could be an option parameter, something like:

`./schema-comparator compare --breaking-exit-code 1 schema_a.graphql schema_b.graphql`

That it could also take an option for `warning-exit-code` if someone wanted to be stricter about what they allow to pass CI.

What do you think?

**Comment by TheMetalCode** [comment]
@tomchipchase @xuorig here's a PR that implements the distinct `verify` command with the exit code, while keeping `compare` unchanged for simple comparison purposes.

https://github.com/xuorig/graphql-schema_comparator/pull/24

**Comment by xuorig** [comment]
I think #24 should be great for this use case, feel free to reopen if you feel something is missing 🙇 Thank you both!

**Pull request closed without merging**
